name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '27 * * * *'

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - name: Install Package Dependencies
      run: |-
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_github('gadenbuie/tweetrmd')"
        Rscript -e "remotes::install_github('rstudio/webshot2')"
        Rscript -e "install.packages('rtweet')"
    - name: Generate Twitter Image
      env:
        ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      run: |-
        Rscript -e "source('get_latest_tweet.R')"
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -m "Built README" -a || echo "No changes to commit"
        git push
